### ISSUE TITLE
No devices found other than CCU3

### ISSUE THREAD

**Issue by Ro4cHii** [danielperna84/hahomematic#1149]
### I agree to the following

- [X] I have read the [documentation](https://github.com/danielperna84/custom_homematic#custom_homematic)
- [X] I am aware of the latest [release notes](https://github.com/danielperna84/custom_homematic/releases)
- [X] The Backend (CCU/Homegear/...) is working as expected and connected devices are controllable by its own UI.
- [X] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello everyone,

although having two UI-controllable thermostats in debmatic, I can only see one single entitiy in Home Assistant (homematic.ccu3) - no devices are being found.

### What version of HomematicIP (local) has the issue?

1.40.1

### What was the last working version of HomematicIP (local)?

This is my first install.

### What type of installation are you running?

Home Assistant Container

### What type of installation are you running for your homematic backend?

debmatic

### Which version of your homematic backend are you running?

3.69.7.108

### What hardware are you running for your system?

Pi4

### Which config details do you use

- [X] Username and password
- [ ] TLS
- [ ] callback data ([see](https://github.com/danielperna84/custom_homematic#callback_host-and-callback_port))

### Which interfaces do you use?

- [ ] Homematic IP
- [X] Homematic (Bidcos-RF)
- [ ] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)

### Diagnostics information

[config_entry-homematicip_local-c26bdc11e2f622c3530aa01a0182186a.json.txt](https://github.com/danielperna84/hahomematic/files/12336485/config_entry-homematicip_local-c26bdc11e2f622c3530aa01a0182186a.json.txt)

### Additional information

- Port has been changed from 80 to 8080
- XML-API has been installed via apt and scripts are executable e.g. via http://192.168.178.26:8080/addons/xmlapi/statelist.cgi

**Comment by SukramJ** [comment]
Please add the full logs.
XmlAPI is not relevant.

Does your CCU User has admin role?

**Comment by Ro4cHii** [comment]
It already is the full logs as downloaded from here:
![image](https://github.com/danielperna84/hahomematic/assets/20772803/99ea2e0b-f419-4976-a771-46052fec538f)

Yes the user has admin role.

**Comment by SukramJ** [comment]
> It already is the full logs as downloaded from here:

Where?

I only see the diagnostics.

**Comment by Ro4cHii** [comment]
Sorry, I misunderstood your question.

Luckily, I figured it out myself after taking a close look into the Home Assitant logs.

I changed the port of the web UI from 80 to 8080 which seemed to cause the error.
After resetting it to 80 it is working now.

However, I really need that port to stay open. Can I somehow reconfigure _custom_homematic_ to work with another port than 80?

**Comment by SukramJ** [comment]
Did you reconfigure the integration to use port 8080 (JsonPort)?

**Comment by Ro4cHii** [comment]
> Did you reconfigure the integration to use port 8080 (JsonPort)?

Thanks a lot! I was not aware that this is the **JSON-RPC Port**. Now everything is working as expected :)
