### ISSUE TITLE
After OS 8.0 > Unable to connect ConnectionRefusedError(111, 'Connection refused')

### ISSUE THREAD

**Issue by marc965** [danielperna84/hahomematic#450]
DONT'T DELETE THIS.
Please answer all questions as good as possible.

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
1.4.0

**Home Assistant version (if applicable):**
2022.5.4, OS 8.0

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...):
- OS (Original, RaspberryMatic, debmatic/...):
- Version: CCU3 RaspberryMatic 3.63.9.20220430

**Problem-relevant configuration:**

Do you use tls?no
Do you use callback?no
Do you use username and password?yes
Which interfaces do you use?rf, hmip, group

**Describe the bug**
Installed OS 8.0.
Integration Homematic(IP) Local dont come up.
Integration down even after several restarts....

**To Reproduce**

**Screenshots (if applicable)**
- CCU firewall
- integrations view
- device view
- enity view

**Relevant HA log entries (full log)**
Logger: hahomematic.central_unit
Source: /usr/local/lib/python3.9/site-packages/hahomematic/central_unit.py:335
First occurred: 14:15:51 (63 occurrences)
Last Logged: 14:25:24
create_client: Failed to create client for central [("Unable to connect ConnectionRefusedError(111, 'Connection refused)...

```

**Diagnostic Information (available on every device)**
```

```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.

**Comment by SukramJ** [comment]
> create_client: Failed to create client for central [("Unable to connect ConnectionRefusedError(111, 'Connection refused).

Why is RaspberryMatic refusing the connection?

**Comment by marc965** [comment]
> 

Dont know! Nothing changed on RaspberryMatic! No "Alarmmeldungen" and no "Systemmeldungen". No issues on Raspberrymatic.

Its only connected with Installation of OS 8.0 i think...
All works correctly before OS 8.0 Update.

**Comment by SukramJ** [comment]
Why don't you add the addon logs?

**Comment by marc965** [comment]
I am not at home! d' ont have 100% access. Only per iPad.
The Addon Logs of RaspberryMatic are normal, no issues there.
The RaspberryMatic Addon is working properly, all devices connected and working.

**Comment by marc965** [comment]
Something strange here.
I tried to reconfigure the Homematic Integration but receive "Verbindung fehlgeschlagen" on saving.

**Comment by SukramJ** [comment]
> Unable to connect ConnectionRefusedError(111, 'Connection refused).

The message indicates that the problem is on your installation, and that the Addon is not reachable from HA.
I cannot give you support for the Addon.

**Comment by marc965** [comment]
What is when the ip Adress of the container changed?

I have it: the Konfiguration of the Homematic integration for the RaspberryMatic is 172.30.33.3.
In the RaspberryMatic Log the ip adress has changed to 172.30.33.4.
Changing to 172.30.33.4 now. Saving is ok.

Integration is now connected!! 

Its because of OS 8.0, the docker container ip address changed...
Is that a possible explanation?

**Comment by marc965** [comment]
i can send you screenshots this evening if it is useful for you?

**Comment by SukramJ** [comment]
If you use the hostname in the configuration it should not matter. 
Name resolution and ip-address assignment is part of HassOS.
Therefor i don't need screenshots.

**Comment by marc965** [comment]
> 

Ok thanks. I think its better to use hostname for that.
Where can i find the real hostname of the RaspberryMatic? 

/AddonScreen/Hostname: de838cd8-raspberrymatic

Is that the correct hostname to fill in?

**Comment by SukramJ** [comment]
You should be save if you follow the [documentation](https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration) by Jens Maus.

**Comment by marc965** [comment]
> You should be save if you follow the [documentation](https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration) by Jens Maus.

OK. Thanks.
All works fine again.

Im am closing this case.

**Comment by marc965** [comment]
Conclusion: Integration Configuration: hostname: fill in hostname not ip-address
